# Generated by Django 4.1.3 on 2022-12-25 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seeker", "0003_appliedjob_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appliedjob",
            name="status",
        ),
    ]
