# Generated by Django 4.1.3 on 2022-11-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0003_profilepic_alter_seekerprofile_profie_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofile',
            name='profie_pic',
            field=models.ImageField(blank=True, upload_to='', verbose_name='/images/'),
        ),
        migrations.DeleteModel(
            name='ProfilePic',
        ),
    ]
