# Generated by Django 4.1.3 on 2022-11-25 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0004_alter_seekerprofile_profie_pic_delete_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, upload_to='', verbose_name='/images/')),
            ],
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='profie_pic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker.profilepic'),
        ),
    ]
