# Generated by Django 4.1.3 on 2022-11-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0007_alter_seekerprofile_profie_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofile',
            name='profie_pic',
            field=models.ImageField(blank=True, default=1, upload_to='', verbose_name='/images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProfilePic',
        ),
    ]
