# Generated by Django 4.1.3 on 2022-11-26 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0003_alter_companycategory_category_name'),
        ('seeker', '0008_alter_seekerprofile_profie_pic_delete_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='superuser.companycategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='country',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='state',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
