# Generated by Django 4.1.3 on 2022-11-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0009_seekerprofile_category_seekerprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofile',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
