# Generated by Django 4.1.3 on 2022-11-26 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0003_alter_companycategory_category_name'),
        ('seeker', '0010_alter_seekerprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superuser.companycategory'),
        ),
    ]
