# Generated by Django 4.1.3 on 2022-11-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0012_appliedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='email',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='first_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='last_name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='phone',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='resume',
            field=models.FileField(default=2, upload_to='resume'),
            preserve_default=False,
        ),
    ]
