# Generated by Django 4.1.3 on 2022-11-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0013_appliedjob_email_appliedjob_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
