# Generated by Django 4.1.3 on 2022-11-28 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0014_alter_appliedjob_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedjob',
            old_name='job',
            new_name='job_id',
        ),
    ]
