# Generated by Django 4.1.3 on 2022-11-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0015_rename_job_appliedjob_job_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedjob',
            old_name='recruiter',
            new_name='recruiter_id',
        ),
        migrations.RenameField(
            model_name='appliedjob',
            old_name='seeker',
            new_name='seeker_id',
        ),
    ]
