# Generated by Django 4.1.3 on 2022-11-28 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0027_rename_company_job_company_id'),
        ('seeker', '0016_rename_recruiter_appliedjob_recruiter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruiter.company'),
            preserve_default=False,
        ),
    ]
