# Generated by Django 4.1.3 on 2022-11-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0021_seekerprofile_department_seekerprofile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='experince',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
