# Generated by Django 4.1.3 on 2022-12-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0022_seekerprofile_experince'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofile',
            name='experince',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
