# Generated by Django 4.1.3 on 2022-12-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0023_alter_seekerprofile_experince'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='shortlisted',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
