# Generated by Django 4.1.3 on 2022-12-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0024_appliedjob_shortlisted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedjob',
            old_name='shortlisted',
            new_name='is_shortlisted',
        ),
    ]
