# Generated by Django 4.1.3 on 2022-12-07 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superuser', '0004_banner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('company_logo', models.ImageField(blank=True, upload_to='media/<django.db.models.fields.CharField>/logo')),
                ('started_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('about', models.TextField(blank=True, max_length=3000)),
                ('founder', models.CharField(blank=True, max_length=200)),
                ('ceo_name', models.CharField(blank=True, max_length=200)),
                ('head_office_location', models.CharField(blank=True, max_length=200)),
                ('security_code', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='superuser.companycategory')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('level', models.CharField(blank=True, choices=[('fresher', 'Fresher'), ('intermediate', 'Intermediate'), ('professional', 'Professional')], default='fresher', max_length=200)),
                ('experience', models.IntegerField(blank=True)),
                ('min_salary', models.IntegerField(blank=True)),
                ('max_salary', models.IntegerField()),
                ('salary_type', models.CharField(blank=True, choices=[('a month', 'a month'), ('a year', 'a year')], default='a year', max_length=200)),
                ('job_type', models.CharField(blank=True, choices=[('part-time', 'Part Time'), ('full-time', 'Full Time'), ('intern', 'Intern'), ('remort', 'Remort'), ('work-from-home', 'Work From Home')], default='full-time', max_length=200)),
                ('full_discription', models.TextField(blank=True)),
                ('short_discription', models.TextField(blank=True)),
                ('schedule', models.CharField(blank=True, max_length=300)),
                ('state', models.CharField(blank=True, max_length=300)),
                ('country', models.CharField(blank=True, max_length=300)),
                ('vacancy', models.IntegerField()),
                ('urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superuser.companycategory')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superuser.companydepartment')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('requirement_2', models.CharField(blank=True, max_length=200)),
                ('requirement_3', models.CharField(blank=True, max_length=200)),
                ('requirement_4', models.CharField(blank=True, max_length=200)),
                ('requirement_5', models.CharField(blank=True, max_length=200)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.job')),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profie_pic', models.ImageField(blank=True, upload_to='', verbose_name='/images/')),
                ('about', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('is_requested', models.BooleanField(blank=True, default=False)),
                ('is_acceped', models.BooleanField(blank=True, default=False)),
                ('is_rejected', models.BooleanField(blank=True, default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superuser.companycategory')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.company')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.qualification'),
        ),
        migrations.AddField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.company')),
                ('recruiter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddRequestSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.companydepartment')),
            ],
        ),
        migrations.CreateModel(
            name='AddRequestDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.companycategory')),
            ],
        ),
    ]
