# Generated by Django 4.1.3 on 2022-11-10 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superuser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('company_logo', models.ImageField(blank=True, upload_to='media/<django.db.models.fields.CharField>/logo')),
                ('started_date', models.DateField(blank=True, null=True)),
                ('about', models.TextField(blank=True, max_length=3000)),
                ('founder', models.CharField(blank=True, max_length=200)),
                ('ceo_name', models.CharField(blank=True, max_length=200)),
                ('ceo_image', models.ImageField(blank=True, upload_to='media/<django.db.models.fields.CharField>/ceo')),
                ('head_office_location', models.CharField(blank=True, max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='superuser.companycategory')),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.company')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
