# Generated by Django 4.1.3 on 2022-11-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='secutity_code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
