# Generated by Django 4.1.3 on 2022-12-08 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShorlistedAppliedSeekers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.job')),
                ('recruiter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiterprofile')),
                ('seeker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
