# Generated by Django 4.1.3 on 2022-11-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_company_secutity_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='secutity_code',
        ),
    ]
