# Generated by Django 4.1.3 on 2022-12-08 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_shorlistedappliedseekers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorlistedappliedseekers',
            name='recruiter_id',
        ),
        migrations.AddField(
            model_name='shorlistedappliedseekers',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruiter.company'),
            preserve_default=False,
        ),
    ]
