# Generated by Django 4.1.3 on 2022-11-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_remove_company_secutity_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='security_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
