# Generated by Django 4.1.3 on 2022-12-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_shorlistedappliedseekers_send'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Basic', max_length=200)),
                ('duration', models.IntegerField(choices=[(30, 'One Month'), (90, 'Three Month')], default=30)),
                ('price', models.CharField(default=0.0, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='plan_expires_in',
            field=models.DateField(blank=True, null=True),
        ),
    ]
