# Generated by Django 4.1.3 on 2022-12-09 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0005_usermembership_recruiterprofile_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipsPurchaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.usermembership')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiterprofile')),
            ],
        ),
    ]
