# Generated by Django 4.1.3 on 2022-12-09 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0006_membershipspurchaces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='plan_expires_in',
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_expires_in', models.DateField(blank=True, null=True)),
                ('paid', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiterprofile')),
            ],
        ),
    ]
