# Generated by Django 4.1.3 on 2022-11-16 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0006_alter_application_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='company',
        ),
        migrations.RemoveField(
            model_name='application',
            name='recruiter',
        ),
    ]
