# Generated by Django 4.1.3 on 2022-11-18 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruiter', '0008_application_company_application_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='recruiter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
