# Generated by Django 4.1.3 on 2022-11-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0010_alter_application_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='started_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
