# Generated by Django 4.1.3 on 2022-12-13 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0011_offerletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.qualification'),
        ),
    ]
