# Generated by Django 4.1.3 on 2022-11-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0011_alter_company_started_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='ceo_image',
        ),
    ]
