# Generated by Django 4.1.3 on 2022-12-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0012_alter_job_qualification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='recruiter',
            new_name='recruiter_id',
        ),
    ]
