# Generated by Django 4.1.3 on 2022-12-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0013_rename_recruiter_job_recruiter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.CharField(blank=True, choices=[('fresher', 'Fresher'), ('intermediate', 'Intermediate'), ('professional', 'Professional')], default='fresher', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='schedule',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
