# Generated by Django 4.1.3 on 2022-11-24 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0014_job_requirements_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='job',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('part-time', 'Part Time'), ('full-time', 'Full Time'), ('intern', 'Intern'), ('remort', 'Remort'), ('work-from-home', 'Work From Home')], default='full-time', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='recruiter.qualification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruiter.requirements'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
