# Generated by Django 4.1.3 on 2022-12-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0014_alter_job_level_alter_job_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
