# Generated by Django 4.1.3 on 2022-11-24 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0016_remove_job_requirements_requirements_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirements',
            name='job',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='requirement_2',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='requirement_3',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='requirement_4',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='requirement_5',
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruiter.requirements'),
            preserve_default=False,
        ),
    ]
