# Generated by Django 4.1.3 on 2022-11-24 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0017_remove_requirements_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
        migrations.AddField(
            model_name='requirements',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruiter.job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requirements',
            name='requirement_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='requirements',
            name='requirement_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='requirements',
            name='requirement_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='requirements',
            name='requirement_5',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
