# Generated by Django 4.1.3 on 2022-11-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0019_addrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='', verbose_name='/images/'),
        ),
    ]
