# Generated by Django 4.1.3 on 2022-11-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0020_recruiterprofile_about_recruiterprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
