# Generated by Django 4.1.3 on 2022-11-26 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0003_alter_companycategory_category_name'),
        ('recruiter', '0021_alter_recruiterprofile_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiterprofile',
            old_name='profile_pic',
            new_name='profie_pic',
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='superuser.companycategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
