# Generated by Django 4.1.3 on 2022-11-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0026_alter_job_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company',
            new_name='company_id',
        ),
    ]
