# Generated by Django 4.1.3 on 2022-11-30 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0031_addrequestskill_addrequestdepartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addrequestdepartment',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='addrequestskill',
            old_name='department',
            new_name='department_id',
        ),
    ]
