# Generated by Django 4.1.3 on 2022-12-01 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0032_rename_category_addrequestdepartment_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addrequestdepartment',
            old_name='category_id',
            new_name='category',
        ),
    ]
