# Generated by Django 4.1.3 on 2022-12-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0033_rename_category_id_addrequestdepartment_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addrequestdepartment',
            old_name='category',
            new_name='category_id',
        ),
    ]
