# Generated by Django 4.1.3 on 2022-12-01 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0003_alter_companycategory_category_name'),
        ('recruiter', '0034_rename_category_addrequestdepartment_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrequestdepartment',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superuser.companycategory'),
        ),
        migrations.AlterField(
            model_name='addrequestskill',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superuser.companydepartment'),
        ),
    ]
