# Generated by Django 4.1.3 on 2022-12-01 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0003_alter_companycategory_category_name'),
        ('recruiter', '0035_alter_addrequestdepartment_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrequestdepartment',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='superuser.companycategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addrequestskill',
            name='department_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='superuser.companydepartment'),
            preserve_default=False,
        ),
    ]
