# Generated by Django 4.1.3 on 2022-12-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0037_rename_category_id_addrequestdepartment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
