# Generated by Django 4.1.3 on 2022-12-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0038_alter_application_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='is_acceped',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='is_requested',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
