# Generated by Django 4.1.3 on 2022-12-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0039_recruiterprofile_is_acceped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
