# Generated by Django 4.1.3 on 2022-12-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0040_alter_application_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='is_rejected',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
