# Generated by Django 4.1.3 on 2022-11-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0002_adminprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycategory',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
