# Generated by Django 4.1.3 on 2022-12-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0003_alter_companycategory_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='/images/')),
            ],
        ),
    ]
